const sqlite3 = require('sqlite3').verbose();
const config = require('config');
const dbPath = config.get('dbPath');
const client_id = config.get('clientId');
const client_secret = config.get('clientSecret');
const request = require('request');
const queryString = require('querystring');
const _ = require('lodash');

const db = new sqlite3.Database(dbPath, sqlite3.OPEN_READWRITE, (err) => {
    if (err) {
        console.error(err.message);
    }
    console.log('Connected to the database.');

    startPlaylistCreation();
});

let authTokens = {};
let userData = {};

async function startPlaylistCreation() {
    await getTokenFromDb();

    // token may be expired. refresh token if first attempt fails.
    try {
        await getUserData();
    } catch (error) {
        await refreshToken();
        await getUserData();
    }

    const shows = await getFollowedPodcasts();
    await createPlaylist(shows);
}

async function createPlaylist(shows) {
    if (shows && shows.items && !_.isEmpty(shows.items)) {
        const playlist = await createEmptyPlaylist();
        const episodes = await getLatestEpisodes(shows);
        addItemsToPlaylist(playlist, episodes);
    } else {
        console.log('No shows.');
    }
}

async function getLatestEpisodes(shows) {
    const episodes = [];
    await Promise.all(shows.items.map(async (item) => {
        try {
            await checkIfShowIsAudioBook(item.show.id);
            const episode = await getEpisode(item.show.id);
            episodes.push(episode);
        } catch (error) {
            console.log(`Error getting episode. show: ${item.show.id}. Error: `, error);
        }
    }));

    return episodes;
}

function checkIfShowIsAudioBook(showId) {
    return new Promise((resolve, reject) => {
        const options = {
            url: `https://api.spotify.com/v1/audiobooks/${showId}`,
            json: true,
            headers: {
                'Authorization': 'Bearer ' + authTokens.access,
                'Content-Type': 'application/json'
            },
        };
        request.get(options, (error, response, body) => {
            if (response.statusCode === 200) {
                reject('This is an audio book.');
            } else {
                resolve();
            }
        });
    });
}

function createEmptyPlaylist() {
    return new Promise((resolve, reject) => {
        const data = JSON.stringify({
            name: `${new Date().toLocaleDateString("en-US")} - latest podcast episodes`,
            description: 'generated by an application'
        });
        const playListOptions = {
            url: `https://api.spotify.com/v1/users/${userData.id}/playlists`,
            json: true,
            headers: {
                'Authorization': 'Bearer ' + authTokens.access,
                'Content-Type': 'application/json'
            },
            form: data

        };
        request.post(playListOptions, (error, response, playlist) => {
            console.log(response.statusMessage);
            if (response.statusCode === 201) {
                resolve(playlist);
            } else {
                reject(response);
            }
        });
    });
}

function getEpisode(showId) {
    return new Promise((resolve, reject) => {
        const options = {
            url: `https://api.spotify.com/v1/shows/${showId}/episodes?${queryString.stringify({
                offset: 0,
                limit: 1
            })}`,
            headers: {
                'Authorization': 'Bearer ' + authTokens.access,
                'Content-Type': 'application/json'
            },
            json: true
        };

        request.get(options, (error, response, episode) => {
            resolve(episode);
        });
    });
}

function addItemsToPlaylist(playList, episodes) {
    console.log('addItemsToPlaylist');
    return new Promise((resolve, reject) => {
        const uris = [];
        episodes.filter((episode) => {
            return !episode.items[0].resume_point.fully_played;
        }).forEach((episode) => {
            uris.push(episode.items[0].uri);
        });
        const data = JSON.stringify({
            uris: uris
        });
        const addToPlaylistOptions = {
            url: playList.tracks.href,
            form: data,
            headers: {
                'Authorization': 'Bearer ' + authTokens.access,
                'Content-Type': 'application/json'
            },
            json: true
        };
        request.post(addToPlaylistOptions, (error, response, body) => {
            console.log(JSON.stringify(body));
        })
    });
}

function getTokenFromDb() {
    console.log('getToken');
    return new Promise((resolve, reject) => {
        db.get('select * from tokens', (err, row) => {
            if (err) {
                console.log('error in getToken() : ', err);
            } else {
                authTokens = row;
                resolve(row);
            }
        })
    });
}

function getFollowedPodcasts() {
    return new Promise((resolve, reject) => {
        console.log('getFollowedPodcasts');
        const options = {
            url: 'https://api.spotify.com/v1/me/shows',
            headers: {
                'Authorization': 'Bearer ' + authTokens.access,
                'Content-Type': 'application/json'
            },
            json: true
        };

        request.get(options, (error, response, body) => {

            if (body.error && body.error.status === 401) {
                reject();
            } else {
                resolve(body);
            }
        });
    });
}

function refreshToken() {
    console.log('refreshToken');
    return new Promise((resolve, reject) => {
        const authOptions = {
            url: 'https://accounts.spotify.com/api/token',
            headers: { 'Authorization': 'Basic ' + (new Buffer(client_id + ':' + client_secret).toString('base64')) },
            form: {
                grant_type: 'refresh_token',
                refresh_token: authTokens.refresh
            },
            json: true
        };

        request.post(authOptions, function (error, response, body) {
            if (!error && response.statusCode === 200) {
                db.run('update tokens set access = ?', body.access_token);
                authTokens.access = body.access_token;
                resolve();
            } else {
                console.log(error);
            }
        });
    });
}

function getUserData() {
    return new Promise((resolve, reject) => {
        console.log('getUserData');
        const options = {
            url: 'https://api.spotify.com/v1/me',
            headers: {
                'Authorization': 'Bearer ' + authTokens.access,
                'Content-Type': 'application/json'
            },
            json: true
        };

        request.get(options, (error, response, body) => {

            if (body.error && body.error.status === 401) {
                reject();
            } else {
                userData = body;
                resolve(body);
            }
        });
    });
}
